apiVersion: v1
kind: Service
metadata:
  name: exoplanet-visualizer-service
spec:
  selector:
    app: exoplanet-visualizer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer